config/routes.rb
Rails.application.routes.draw do
  # BOOKMARK ROUTES
  # get 'lists/:list_id/bookmarks', to: 'bookmarks#index'
  # get 'lists/:list_id/bookmarks/new', to: 'bookmarks#new'
  # post 'lists/:list_id/bookmarks', to: 'bookmarks#create'
  # get 'bookmarks/:id', to: 'bookmarks#destroy'
  # # get 'bookmarks/:id', to: 'bookmarks#show', as: :bookmark

  # # LIST ROUTES
  # get 'lists', to: 'lists#index'
  # get 'lists/new', to: 'lists#new'
  # post 'lists', to: 'lists#create'
  # delete 'lists/:id', to: 'lists#destroy'
  # get 'lists/:id', to: 'lists#show', as: :list

  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, notice: 'Try again - not able to add bookmark'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to bookmark_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save
    redirect_to movie_path(@movie)
  end

  def show
    @movie = Movie.find(params[:id])
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Create A New Bookmark</h1>
<%#= render 'bookmarks/form' %>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(cinema_banner.jpeg);">
  <div class="container">
    <h1>My Movie Lists</h1>
  </div>
</div>


<div class="container">


<div class="row justify-center-between">
  <% @lists.each do |list| %>
    <div class="col-3 card border p-3 m-2">
      <%= link_to list.name, list_path(list) %>
    </div>
    <% end %>
</div>

<div>
  <%= link_to new_list_path, class: "btn btn-primary" do %>
    <span>Create a movie list</span>
    <i class="fa-solid fa-plus"></i>
  <% end %>
</div>

</div>

app/views/lists/new.html.erb
<h1>Create A New List</h1>
<%= render 'form', list: @list %>

app/views/lists/show.html.erb
<h1> <%= @list.name %> </h1>

<%= link_to "Delete List",
  list_path(@list),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<%= link_to "Create New List", new_list_bookmark_path(@list), class: "" %>

<div class="container">

  <div class="d-flex justify-content-between">
  <% @list.movies.each do |movie| %>
    <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
    <div class="card rounded-lg p-2 mx-2">
      <h2><%= bookmark.movie.title %></h2>
      <p><%= bookmark.movie.rating %>/5 ⭐️</p>
      <p><%= bookmark.movie.overview %></p>
      <img src="<%= bookmark.movie.poster_url %>" alt="Poster" width="150px">
      <div>
        <i class="fa-solid fa-quote-left"></i>
        <span class="font-italic"><%= bookmark.comment %></span>
      </div>
      <div>
        <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </div>


    </div>
  <% end %>

</div>
</div>